### ISSUE TITLE
[openstack] connector fails on VMs w/ 'requests' package

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#155]
Failure is in [1].  Test run https://nuv.la/run/ba4567e5-6cf0-4bf1-af75-7a33813fd2df.

Connector should either bring `requests` or install them when on the VM.  

An idea would be - to extend `slipstream.bootstrap` and cloud client tarballs to have requirement.txt file what would be called by `slipstream.bootstrap` after downloading and unpacking the cloud client on Orch. 

`pip install -r /opt/<cloud>/requirement.txt`.

[1]. No reports were produced.  The log was collected directly from Orch in another debug run w/ termination of VMs on failure. This is topic for another issue.

```
root@orchestrator-open-telekom-de1ba4567e5-6cf0-4bf1-af75-7a33813fd:~# cat /var/log/slipstream/client/slipstream-orchestrator.log
started with pid 7361

: 2017-05-26T08:31:35Z :
ERROR: Failing... Machine executor creation failed: No module named requests
Traceback (most recent call last):
  File "/opt/slipstream/client/lib/slipstream/executors/Machine.py", line 37, in execute
    executor = self.executorFactory.createExecutor(self.configHolder)
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorExecutorFactory.py", line 34, in createExecutor
    cloudWrapper.initCloudConnector(configHolder)
  File "/opt/slipstream/client/lib/slipstream/wrappers/CloudWrapper.py", line 58, in initCloudConnector
    config_holder or self._get_config_holder())
  File "/opt/slipstream/client/lib/slipstream/cloudconnectors/CloudConnectorFactory.py", line 37, in createConnector
    mod = loadModule(get_connector_module_name(configHolder))
  File "/opt/slipstream/client/lib/slipstream/util.py", line 536, in loadModule
    return __import__(name, fromlist=namespace)
  File "/opt/otc/slipstream_otc/OpenTelekomClientCloud.py", line 22, in <module>
    import requests
ImportError: No module named requests
2017-05-26 08:31:35,819:CRITICAL:NodeExecutor:Traceback (most recent call last):
  File "/opt/slipstream/client/lib/slipstream/daemonr/DaemonRunner.py", line 35, in __init__
    self.run_action(runnable)
  File "/opt/slipstream/client/lib/slipstream/daemonr/DaemonRunner.py", line 61, in run_action
    self.do_action()
  File "/opt/slipstream/client/lib/daemon/runner.py", line 267, in do_action
    func(self)
  File "/opt/slipstream/client/lib/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 125, in run
    self._executor.do_work()
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 93, in do_work
    self._callAndHandleErrorsForCommands(self.doWork.__name__)
  File "/opt/slipstream/client/lib/slipstream/command/CommandBase.py", line 136, in _callAndHandleErrorsForCommands
    res = self.__class__.__dict__[methodName](self, *args, **kw)
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 98, in doWork
    orchestrator.execute()
  File "/opt/slipstream/client/lib/slipstream/executors/Machine.py", line 39, in execute
    self._publish_abort_and_fail("Machine executor creation failed", ex)
  File "/opt/slipstream/client/lib/slipstream/executors/Machine.py", line 46, in _publish_abort_and_fail
    raise exception
ImportError: No module named requests

2017-05-26 08:31:35,819:CRITICAL:NodeExecutor:Traceback (most recent call last):
  File "/opt/slipstream/client/lib/slipstream/daemonr/DaemonRunner.py", line 35, in __init__
    self.run_action(runnable)
  File "/opt/slipstream/client/lib/slipstream/daemonr/DaemonRunner.py", line 61, in run_action
    self.do_action()
  File "/opt/slipstream/client/lib/daemon/runner.py", line 267, in do_action
    func(self)
  File "/opt/slipstream/client/lib/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 125, in run
    self._executor.do_work()
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 93, in do_work
    self._callAndHandleErrorsForCommands(self.doWork.__name__)
  File "/opt/slipstream/client/lib/slipstream/command/CommandBase.py", line 136, in _callAndHandleErrorsForCommands
    res = self.__class__.__dict__[methodName](self, *args, **kw)
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 98, in doWork
    orchestrator.execute()
  File "/opt/slipstream/client/lib/slipstream/executors/Machine.py", line 39, in execute
    self._publish_abort_and_fail("Machine executor creation failed", ex)
  File "/opt/slipstream/client/lib/slipstream/executors/Machine.py", line 46, in _publish_abort_and_fail
    raise exception
ImportError: No module named requests

Traceback (most recent call last):
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 133, in <module>
    DaemonRunner(runnable)
  File "/opt/slipstream/client/lib/slipstream/daemonr/DaemonRunner.py", line 35, in __init__
    self.run_action(runnable)
  File "/opt/slipstream/client/lib/slipstream/daemonr/DaemonRunner.py", line 61, in run_action
    self.do_action()
  File "/opt/slipstream/client/lib/daemon/runner.py", line 267, in do_action
    func(self)
  File "/opt/slipstream/client/lib/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 125, in run
    self._executor.do_work()
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 93, in do_work
    self._callAndHandleErrorsForCommands(self.doWork.__name__)
  File "/opt/slipstream/client/lib/slipstream/command/CommandBase.py", line 136, in _callAndHandleErrorsForCommands
    res = self.__class__.__dict__[methodName](self, *args, **kw)
  File "/opt/slipstream/client/sbin/slipstream-orchestrator", line 98, in doWork
    orchestrator.execute()
  File "/opt/slipstream/client/lib/slipstream/executors/Machine.py", line 39, in execute
    self._publish_abort_and_fail("Machine executor creation failed", ex)
  File "/opt/slipstream/client/lib/slipstream/executors/Machine.py", line 46, in _publish_abort_and_fail
    raise exception
ImportError: No module named requests
root@orchestrator-open-telekom-de1ba4567e5-6cf0-4bf1-af75-7a33813fd:~#
```

**Comment by konstan** [comment]
Now it fails with

```
ss:abort- Machine executor creation failed: ImportError: No module named requests
```
