### ISSUE TITLE
[cloudstack] _vm_get_id and _vm_get_ip should expect either map or CloudStackNode

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#173]
Some parts of the code pass vm parameter as map others CloudStackNode (from libcloud).

```
ERROR: Error executing node, with detail: 'CloudStackNode' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/opt/slipstream/client/lib/slipstream/executors/MachineExecutor.py", line 106, in _execute_state
    getattr(self, method_name)()
  File "/opt/slipstream/client/lib/slipstream/util.py", line 118, in overrided_func
    return func(self, *args, **kwargs)
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 41, in onProvisioning
    self._start_instances()
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 89, in _start_instances
    self._run_instances_action(self.wrapper.start_node_instances, 'starting')
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 111, in _run_instances_action
    action()
  File "/opt/slipstream/client/lib/slipstream/wrappers/CloudWrapper.py", line 89, in start_node_instances
    self._check_provisioning(nodes_instances_list)
  File "/opt/slipstream/client/lib/slipstream/wrappers/CloudWrapper.py", line 136, in _check_provisioning
    self._get_state_timeout_time(), node_instances, allowed_failed_vms_per_node)
  File "/opt/slipstream/client/lib/slipstream/wrappers/CloudWrapper.py", line 182, in _sleep_while_instances_provisioned
    instances_failed_iaas = self._get_failed_instances_on_iaas(node_instances)
  File "/opt/slipstream/client/lib/slipstream/wrappers/CloudWrapper.py", line 277, in _get_failed_instances_on_iaas
    vm_id = self._cloud_client._vm_get_id(vm)
  File "/opt/slipstream/client/lib/slipstream/util.py", line 118, in overrided_func
    return func(self, *args, **kwargs)
  File "/opt/exoscale/slipstream_cloudstack/CloudStackClientCloud.py", line 234, in _vm_get_id
    return vm['id']
TypeError: 'CloudStackNode' object has no attribute '__getitem__'
```

**Comment by konstan** [comment]
Closing this issue.  A fix was provided in https://github.com/slipstream/SlipStreamClient/pull/361.  The followup issue proposing a more generic solution is here https://github.com/slipstream/SlipStreamClient/issues/362
