### ISSUE TITLE
[openstack] Bad Request Invalid input for field/attribute availability_zone. Value: None.

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#202]
This fails on ifb-cloud - https://nuv.la/run/002eba37-4423-4b83-be5e-abe4499c9613
```
: 2018-02-21T11:12:48Z : 
ERROR: Failing... Exception <class 'libcloud.common.exceptions.BaseHTTPError'> with detail: 400 Bad Request Invalid input for field/attribute availability_zone. Value: None. None is not of type 'string'
Traceback (most recent call last):
  File "/opt/slipstream/client/lib/slipstream/executors/MachineExecutor.py", line 106, in _execute_state
    getattr(self, method_name)()
  File "/opt/slipstream/client/lib/slipstream/util.py", line 119, in overrided_func
    return func(self, *args, **kwargs)
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 41, in onProvisioning
    self._start_instances()
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 89, in _start_instances
    self._run_instances_action(self.wrapper.start_node_instances, 'starting')
  File "/opt/slipstream/client/lib/slipstream/executors/orchestrator/OrchestratorDeploymentExecutor.py", line 111, in _run_instances_action
    action()
  File "/opt/slipstream/client/lib/slipstream/wrappers/CloudWrapper.py", line 84, in start_node_instances
    self._get_user_info(self._get_cloud_service_name()), nodes_instances)
  File "/opt/slipstream/client/lib/slipstream/wrappers/CloudWrapper.py", line 106, in _start_nodes_and_clients
    self._cloud_client.start_nodes_and_clients(user_info, nodes_instances)
  File "/opt/slipstream/client/lib/slipstream/cloudconnectors/BaseCloudConnector.py", line 435, in start_nodes_and_clients
    nodes_instances)
  File "/opt/slipstream/client/lib/slipstream/cloudconnectors/BaseCloudConnector.py", line 442, in __start_nodes_instantiation_tasks_wait_finished
    self.__wait_nodes_startup_tasks_finished()
  File "/opt/slipstream/client/lib/slipstream/cloudconnectors/BaseCloudConnector.py", line 456, in __wait_nodes_startup_tasks_finished
    self.__tasks_runnner.wait_tasks_processed()
  File "/opt/slipstream/client/lib/slipstream/utils/tasksrunner.py", line 58, in wait_tasks_processed
    self._process_exc_queue(ignore_exception)
  File "/opt/slipstream/client/lib/slipstream/utils/tasksrunner.py", line 114, in run
    super(ThreadWrapper, self).run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/slipstream/client/lib/slipstream/utils/tasksrunner.py", line 92, in work
    self._executor(*task)
  File "/opt/slipstream/client/lib/slipstream/cloudconnectors/BaseCloudConnector.py", line 465, in __start_node_instance_and_client
    self._generate_vm_name(node_instance_name))
  File "/opt/slipstream/client/lib/slipstream/util.py", line 119, in overrided_func
    return func(self, *args, **kwargs)
  File "/opt/openstack/slipstream_openstack/OpenStackClientCloud.py", line 203, in _start_image
    return self._start_image_on_openstack(user_info, node_instance, vm_name)
  File "/opt/openstack/slipstream_openstack/OpenStackClientCloud.py", line 253, in _start_image_on_openstack
    location=self._get_service_name(user_info))
  File "/opt/openstack/slipstream_openstack/OpenStackLibcloudPatch.py", line 426, in create_volume
    data={'volume': volume})
  File "/opt/openstack/libcloud/common/openstack.py", line 202, in request
    raw=raw)
  File "/opt/openstack/libcloud/common/base.py", line 799, in request
    response = responseCls(**kwargs)
  File "/opt/openstack/libcloud/compute/drivers/openstack.py", line 1001, in __init__
    super(OpenStack_1_1_Response, self).__init__(*args, **kwargs)
  File "/opt/openstack/libcloud/common/base.py", line 143, in __init__
    headers=self.headers)
BaseHTTPError: 400 Bad Request Invalid input for field/attribute availability_zone. Value: None. None is not of type 'string'
```

**Comment by konstan** [comment]
Demoting from bug to enhancement and putting to backlog.
