### ISSUE TITLE
build fails on clean environment

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamConnectors#209]
The build of the `SlipStreamConnectors/cloudstack/python/tar` module (and probably all other similar modules) fails because of a dependency on `slipstream-api`, that isn't installed in the build process. It looks like the current CI has this installed manually and is using a fixed version for the build.  In addition, the connectors also require the explicit installation of `nose` and `coverage`, rather than an automatic installation via `tox`. 

The traceback is the following:
```
======================================================================
ERROR: Failure: ImportError (No module named api)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/root/SlipStreamConnectors/cloudstack/python/tar/test/TestCloudStackClientCloud.py", line 23, in <module>
    from slipstream_cloudstack.CloudStackClientCloud import CloudStackClientCloud
  File "/root/SlipStreamConnectors/cloudstack/python/tar/slipstream_cloudstack/CloudStackClientCloud.py", line 33, in <module>
    from slipstream.cloudconnectors.BaseCloudConnector import BaseCloudConnector
  File "/root/SlipStreamConnectors/cloudstack/python/tar/target/dependencies/slipstream-client/lib/slipstream/cloudconnectors/BaseCloudConnector.py", line 39, in <module>
    from slipstream.wrappers.BaseWrapper import NodeInfoPublisher
  File "/root/SlipStreamConnectors/cloudstack/python/tar/target/dependencies/slipstream-client/lib/slipstream/wrappers/BaseWrapper.py", line 24, in <module>
    from slipstream.SlipStreamHttpClient import SlipStreamHttpClient
  File "/root/SlipStreamConnectors/cloudstack/python/tar/target/dependencies/slipstream-client/lib/slipstream/SlipStreamHttpClient.py", line 27, in <module>
    from slipstream.HttpClient import HttpClient
  File "/root/SlipStreamConnectors/cloudstack/python/tar/target/dependencies/slipstream-client/lib/slipstream/HttpClient.py", line 37, in <module>
    from slipstream.api import Api
ImportError: No module named api

----------------------------------------------------------------------
XML: /root/SlipStreamConnectors/cloudstack/python/tar/nosetests.xml
Name                                               Stmts   Miss  Cover
----------------------------------------------------------------------
slipstream_cloudstack/LibcloudCloudstackPatch.py      92     81    12%
slipstream_cloudstack/__init__.py                      0      0   100%
----------------------------------------------------------------------
TOTAL                                                 92     81    12%
----------------------------------------------------------------------
Ran 1 test in 0.492s
```

**Comment by loomis** [comment]
This can be reproduced with:
```
docker run -it sixsq/slipstream:build
```
to start a container and then:
```
git clone https://github.com/slipstream/SlipStreamConnectors.git 
cd SlipStreamConnectors/
mvn clean install 
```
to do that actual build.
